const Constants = {
    CREATING_GRID: 'CREATING_GRID',
    ROTATING_NODE: 'ROTATING_NODE',
    CHANGING_TEMP_1: 'CHANGING_TEMP_1',
    CHANGING_TEMP_2: 'CHANGING_TEMP_2',
    CHANGING_TEMP_3: 'CHANGING_TEMP_3',
    CHANGING_TEMP_4: 'CHANGING_TEMP_4',
    LOADING_OPTIONS: 'LOADING_OPTIONS',
    SPREADING_WATER: 'SPREADING_WATER',
    LOADING_SCORES: 'LOADING_SCORES',
    LOADING_FIREBASE: 'LOADING_FIREBASE',
    TOGGLE_ONCE: 'TOGGLE_ONCE'
}
export default Constants;
